const CATEGORIES = [
  {
    "slug": "elektronica",
    "name": "Elektronica pallets",
    "image": "assets/products/pallet-electronics.jpg",
    "blurb": "Retour- en overstocklots met laptops, audio, monitors en accessoires. Manifest per artikel."
  },
  {
    "slug": "high-count",
    "name": "High Count FC pallets",
    "image": "assets/products/pallet-gaylord.jpg",
    "blurb": "Hoge gaylord-stapels gemengde fulfillment-retouren. Geen itemmanifest, lagere stukprijs."
  },
  {
    "slug": "sneakers",
    "name": "Sneaker pallets",
    "image": "assets/products/pallet-sneakers.jpg",
    "blurb": "Sport- en lifestyle schoeisel met merk, model, kleurweg en maatreks in het manifest."
  },
  {
    "slug": "kleding",
    "name": "Kleding en mode",
    "image": "assets/products/pallet-clothing.jpg",
    "blurb": "Merkkleding in nieuwe of tagged staat. Partijen van 250 stuks tot volle pallets."
  },
  {
    "slug": "keuken",
    "name": "Huishoudapparaten",
    "image": "assets/products/pallet-kitchen.jpg",
    "blurb": "Koffiemachines, mixers, stofzuigers en airfryers. Conditieklasse per toestel."
  },
  {
    "slug": "gereedschap",
    "name": "Gereedschap pallets",
    "image": "assets/products/pallet-tools.jpg",
    "blurb": "Accu- en handgereedschap voor wederverkoop via marktplaatsen en bouwgroothandel."
  },
  {
    "slug": "parfum",
    "name": "Parfum en cosmetica",
    "image": "assets/products/pallet-perfume.jpg",
    "blurb": "Geur, huid- en haarverzorging in verzegelde of testerstaat. Volledige SKU-lijst."
  },
  {
    "slug": "iphone",
    "name": "Smartphone pallets",
    "image": "assets/products/pallet-phones.jpg",
    "blurb": "iPhone- en Android-lots met model, opslag, kleur en batterijstatus vóór aankoop."
  },
  {
    "slug": "speelgoed",
    "name": "Speelgoed en collectibles",
    "image": "assets/products/pallet-toys.jpg",
    "blurb": "Bouwsets, kaarten en seizoensspeelgoed. Geschikt voor webshops en kermissen."
  },
  {
    "slug": "mystery-box",
    "name": "Mystery box pallets",
    "image": "assets/products/pallet-mystery.jpg",
    "blurb": "Gemengde retourdozen. Inhoud varieert; conditie van nieuw tot salvage."
  },
  {
    "slug": "airco",
    "name": "Airco en HVAC",
    "image": "assets/products/pallet-airco.jpg",
    "blurb": "Draagbare en split-units uit overstock en retourprogramma's."
  },
  {
    "slug": "winterschoenen",
    "name": "Winterschoenen",
    "image": "assets/products/pallet-winter.jpg",
    "blurb": "Laarzen en gevoerde schoenen voor het najaar. Maatreks in het manifest."
  }
];
const PRODUCTS = [
  {
    "slug": "elektronica-retourdoos-24",
    "name": "Retourdoos elektronica – 24 stuks – MSRP €4.650",
    "category": "elektronica",
    "price": 1322.0,
    "msrp": 4650,
    "items": 24,
    "condition": "Retour / gemengd",
    "badge": "Manifest",
    "image": "assets/products/pallet-electronics.jpg",
    "short": "Geteste en ongeteste consumentenelektronica in een compacte doos. Volledig artikelmanifest.",
    "body": "Deze doos is bedoeld voor verkopers die snel willen listen op eBay.de of Bol. Elk artikel staat in het manifest met merk, model en conditieklasse. Reken op een mix van audio, randapparatuur en kleine IT-accessoires."
  },
  {
    "slug": "monitor-salvage-19",
    "name": "Salvage monitorpallet – 19 stuks – MSRP €6.300",
    "category": "elektronica",
    "price": 535.03,
    "msrp": 6300,
    "items": 19,
    "condition": "Salvage",
    "badge": "Salvage",
    "image": "assets/products/pallet-monitors.jpg",
    "short": "Schermen met cosmetische of functionele schade. Alleen voor reparatie of onderdelen.",
    "body": "Niet geschikt als eerste aankoop. De lotomschrijving vermeldt schermmaat en merk waar bekend. Kopers met een reparatielijn halen hier de hoogste restwaarde uit."
  },
  {
    "slug": "toetsenborden-defect-15",
    "name": "Defecte toetsenborden – 15 stuks – MSRP €2.204",
    "category": "elektronica",
    "price": 311.39,
    "msrp": 2204,
    "items": 15,
    "condition": "Salvage",
    "badge": "Salvage",
    "image": "assets/products/pallet-electronics.jpg",
    "short": "Kleine salvage-box voor onderdelen of refurbishment.",
    "body": "Vijftien gaming- en kantoortoetsenborden met uiteenlopende gebreken. Manifest vermeldt visuele staat. Verkoop as-is of strip voor switches en behuizingen."
  },
  {
    "slug": "elektronica-pallet-43",
    "name": "Elektronica retourpallet – 43 stuks – MSRP €10.625",
    "category": "elektronica",
    "price": 1890.0,
    "msrp": 10625,
    "items": 43,
    "condition": "Retour",
    "badge": "Manifest",
    "image": "assets/products/pallet-electronics.jpg",
    "short": "Middelgroot elektronicalot met ASIN-lijst vóór betaling.",
    "body": "Mix van headphones, speakers, webcams en smart-home items. Conditie loopt van nieuw-in-doos tot gebruikte retour. Uitvalpercentage staat in de lotnotitie."
  },
  {
    "slug": "high-count-12",
    "name": "High Count Gaylord #12",
    "category": "high-count",
    "price": 3000.0,
    "msrp": null,
    "items": null,
    "condition": "Gemengd / as-is",
    "badge": "Geen manifest",
    "image": "assets/products/pallet-gaylord.jpg",
    "short": "Hoge gaylord van fulfillment-retouren. Geen itemlijst, vaste prijs.",
    "body": "Stapel van circa 1,8 tot 2,1 meter. Categorieën kunnen elektronica, speelgoed, textiel en huishoud zijn. Alleen voor ervaren sorteerders. Verkoop is definitief."
  },
  {
    "slug": "high-count-18",
    "name": "High Count Gaylord #18",
    "category": "high-count",
    "price": 1980.0,
    "msrp": null,
    "items": null,
    "condition": "Gemengd / as-is",
    "badge": "Geen manifest",
    "image": "assets/products/pallet-gaylord.jpg",
    "short": "Tweede gaylord in dezelfde reeks, andere mix, zelfde voorwaarden.",
    "body": "Geen veiling en geen bieden. Beschikbaar zolang de voorraad strekt. Vracht wordt na adresbevestiging berekend."
  },
  {
    "slug": "high-count-21",
    "name": "High Count Gaylord #21",
    "category": "high-count",
    "price": 1171.97,
    "msrp": null,
    "items": null,
    "condition": "Gemengd / as-is",
    "badge": "Geen manifest",
    "image": "assets/products/pallet-amazon-boxes.jpg",
    "short": "Compactere high-count voor wie volume wil testen zonder truckload.",
    "body": "Lagere instapprijs dan de 3.000-euro gaylords. Nog steeds zonder artikelmanifest. Niet aanbevolen voor beginners."
  },
  {
    "slug": "high-count-27",
    "name": "High Count Gaylord #27",
    "category": "high-count",
    "price": 2320.0,
    "msrp": null,
    "items": null,
    "condition": "Gemengd / as-is",
    "badge": "Geen manifest",
    "image": "assets/products/pallet-gaylord.jpg",
    "short": "Standaard FC-hoogte, gemengde merchandise, directe verzending.",
    "body": "Geschikt voor veilingoperators en export. Verwacht een breed conditiebereik van nieuw tot onverkoopbaar."
  },
  {
    "slug": "sneaker-mixed-120",
    "name": "Gemengde sneakerpallet – 120 paar",
    "category": "sneakers",
    "price": 2140.0,
    "msrp": 9600,
    "items": 120,
    "condition": "Nieuw / overstock",
    "badge": "Manifest",
    "image": "assets/products/pallet-sneakers.jpg",
    "short": "Atletisch en lifestyle schoeisel met maat- en kleuroverzicht.",
    "body": "Merken wisselen per lot. Het manifest noemt modelnamen en EU-maten. Populaire exitkanalen: Vinted, eBay.de en fysieke outlets."
  },
  {
    "slug": "sneaker-premium-80",
    "name": "Premium lifestyle sneakers – 80 paar",
    "category": "sneakers",
    "price": 2680.0,
    "msrp": 11200,
    "items": 80,
    "condition": "Nieuw in doos",
    "badge": "Nieuw",
    "image": "assets/products/pallet-sneakers.jpg",
    "short": "Hogere retailwaarde per paar, volledige doospresentatie.",
    "body": "Kleinere teller, hogere stukprijs. Bedoeld voor boutiques en sneakerresellers die liever minder volume en schonere lots hebben."
  },
  {
    "slug": "hardloop-overstock-96",
    "name": "Hardloopschoenen overstock – 96 paar",
    "category": "sneakers",
    "price": 1750.0,
    "msrp": 7680,
    "items": 96,
    "condition": "Nieuw",
    "badge": "Overstock",
    "image": "assets/products/pallet-sneakers.jpg",
    "short": "Seizoensoverstock uit Europese distributie.",
    "body": "Vooral neutrale kleuren en middensegment. Maatreks loopt van 38 tot 46, details in het Excel-manifest."
  },
  {
    "slug": "kleding-merk-250-a",
    "name": "Merkkleding pallet #3 – 250 stuks",
    "category": "kleding",
    "price": 1592.47,
    "msrp": 8750,
    "items": 250,
    "condition": "Nieuw met tags",
    "badge": "250 stuks",
    "image": "assets/products/pallet-clothing.jpg",
    "short": "Dames- en herenmix, tagged, klaar voor rek of online listing.",
    "body": "Geen replica's. Maattabel en merksplit staan in het manifest. Geschikt voor weekmarkten en outletshops."
  },
  {
    "slug": "kleding-merk-250-b",
    "name": "Merkkleding pallet #4 – 250 stuks",
    "category": "kleding",
    "price": 1211.0,
    "msrp": 7200,
    "items": 250,
    "condition": "Nieuw met tags",
    "badge": "250 stuks",
    "image": "assets/products/pallet-clothing.jpg",
    "short": "Tweede kledinglot uit dezelfde reeks, andere merkmix.",
    "body": "Lagere instapprijs door meer basics. Controleer het seizoen in de lotomschrijving voordat je bestelt."
  },
  {
    "slug": "kleding-merk-250-c",
    "name": "Merkkleding pallet #7 – 250 stuks",
    "category": "kleding",
    "price": 1242.75,
    "msrp": 6900,
    "items": 250,
    "condition": "Nieuw / overstock",
    "badge": "250 stuks",
    "image": "assets/products/pallet-clothing.jpg",
    "short": "Casual en sportkleding, tagged of in polybag.",
    "body": "Goede starter voor Vinted-verkopers die volume willen zonder truckload. Retouren na verzending worden niet geaccepteerd."
  },
  {
    "slug": "kleding-warehouse-400",
    "name": "Warehouse modepallet – 400 stuks",
    "category": "kleding",
    "price": 1890.0,
    "msrp": 11000,
    "items": 400,
    "condition": "Nieuw / mixed",
    "badge": "Volume",
    "image": "assets/products/pallet-clothing.jpg",
    "short": "Hoger volume voor distributeurs die splitsen naar lokale winkels.",
    "body": "Bevat meerdere merklagen. Vraag het Excel-bestand aan vóór betaling via sales@pallethaven.nl."
  },
  {
    "slug": "keuken-mix-36",
    "name": "Keukenapparatuur mix – 36 stuks",
    "category": "keuken",
    "price": 1480.0,
    "msrp": 7200,
    "items": 36,
    "condition": "Nieuw / open box",
    "badge": "Manifest",
    "image": "assets/products/pallet-kitchen.jpg",
    "short": "Airfryers, mixers en koffieapparaten met modelnummers in het manifest.",
    "body": "Populair bij Facebook Marketplace-verkopers. Controleer voltage (230V) in de specificaties; alle lots voor de EU-markt zijn 230V tenzij anders vermeld."
  },
  {
    "slug": "stofzuiger-overstock-20",
    "name": "Stofzuiger overstock – 20 stuks",
    "category": "keuken",
    "price": 980.0,
    "msrp": 5400,
    "items": 20,
    "condition": "Nieuw verzegeld",
    "badge": "Nieuw",
    "image": "assets/products/pallet-kitchen.jpg",
    "short": "Steel- en cilinderstofzuigers, fabrieksverzegeld.",
    "body": "Beperkte merkmix, hoge herkenning. Accessoires volgens doosinhoud; ontbrekende onderdelen worden in het manifest gemeld."
  },
  {
    "slug": "koffie-pallet-28",
    "name": "Koffiemachine pallet – 28 stuks",
    "category": "keuken",
    "price": 1625.0,
    "msrp": 8900,
    "items": 28,
    "condition": "Nieuw / retour",
    "badge": "Manifest",
    "image": "assets/products/pallet-kitchen.jpg",
    "short": "Volautomaten en capsuleapparaten, conditie per serienummer.",
    "body": "Open-box toestellen zijn visueel gecontroleerd. Functionele garanties van de fabrikant kunnen vervallen bij liquidatievoorraad."
  },
  {
    "slug": "gereedschap-accu-mix",
    "name": "Accugereedschap mixpallet",
    "category": "gereedschap",
    "price": 1540.0,
    "msrp": 6800,
    "items": 42,
    "condition": "Nieuw / overstock",
    "badge": "Manifest",
    "image": "assets/products/pallet-tools.jpg",
    "short": "Boormachines, slijpers en combosets. Accu's vermeld waar aanwezig.",
    "body": "Niet alle sets bevatten accu en lader. Het manifest maakt dat per regel zichtbaar zodat je je inkoopprijs per werkende kit kunt rekenen."
  },
  {
    "slug": "handgereedschap-bulk",
    "name": "Handgereedschap bulkpallet",
    "category": "gereedschap",
    "price": 890.0,
    "msrp": 3100,
    "items": 180,
    "condition": "Nieuw",
    "badge": "Bulk",
    "image": "assets/products/pallet-tools.jpg",
    "short": "Tangen, sleutels, bitsets en opbergkoffers.",
    "body": "Lage stukprijs, breed assortiment. Geschikt voor bouwmarkten en marktkramen. Geen elektrische apparaten in dit lot."
  },
  {
    "slug": "job-site-combo",
    "name": "Jobsite combo – 30 kits",
    "category": "gereedschap",
    "price": 2110.0,
    "msrp": 9400,
    "items": 30,
    "condition": "Nieuw in doos",
    "badge": "Nieuw",
    "image": "assets/products/pallet-tools.jpg",
    "short": "Combopacks voor wederverkoop aan ZZP'ers en webshops.",
    "body": "Elke kit is als één SKU te listen. Voltage en accuplatform staan in het manifest."
  },
  {
    "slug": "parfum-100",
    "name": "Parfumpallet – 100 stuks",
    "category": "parfum",
    "price": 1280.0,
    "msrp": 6200,
    "items": 100,
    "condition": "Nieuw verzegeld",
    "badge": "Nieuw",
    "image": "assets/products/pallet-perfume.jpg",
    "short": "Designer- en masstige geuren, verzegelde flacons.",
    "body": "Geen testers in dit lot. Batchcodes waar beschikbaar. Parallelimport mogelijk; controleer lokale etikettering voor jouw verkoopkanaal."
  },
  {
    "slug": "beauty-mix-180",
    "name": "Beauty mixpallet – 180 stuks",
    "category": "parfum",
    "price": 960.0,
    "msrp": 4100,
    "items": 180,
    "condition": "Nieuw",
    "badge": "Mix",
    "image": "assets/products/pallet-cosmetics.jpg",
    "short": "Huid, haar en make-up. THT-data in het spreadsheet.",
    "body": "Let op houdbaarheidsdata. Lots met minder dan zes maanden THT worden als zodanig gemarkeerd."
  },
  {
    "slug": "iphone-grade-a-12",
    "name": "Smartphone Grade A – 12 stuks",
    "category": "iphone",
    "price": 3240.0,
    "msrp": 9600,
    "items": 12,
    "condition": "Grade A refurbished",
    "badge": "Grade A",
    "image": "assets/products/pallet-phones.jpg",
    "short": "Geteste toestellen met batterijgezondheid in het manifest.",
    "body": "IMEI-lijst volgt na reservering. Cosmetisch hoog, functioneel getest. Niet nieuw verzegeld tenzij expliciet vermeld."
  },
  {
    "slug": "iphone-nieuw-8",
    "name": "Nieuwe smartphones – 8 stuks",
    "category": "iphone",
    "price": 4120.0,
    "msrp": 10300,
    "items": 8,
    "condition": "Nieuw verzegeld",
    "badge": "Nieuw",
    "image": "assets/products/pallet-phones.jpg",
    "short": "Fabrieksverzegelde retaildozen, EU-stekker.",
    "body": "Beperkte voorraad. Model en opslag per seriële regel. Identiteitsverificatie kan worden gevraagd bij high-value lots."
  },
  {
    "slug": "wearables-24",
    "name": "Wearables en watches – 24 stuks",
    "category": "iphone",
    "price": 1180.0,
    "msrp": 4800,
    "items": 24,
    "condition": "Nieuw / retour",
    "badge": "Manifest",
    "image": "assets/products/pallet-phones.jpg",
    "short": "Smartwatches en bands, mix van nieuw en open box.",
    "body": "Bandjesmaten en kastmaten staan in het bestand. Geschikt als add-on bij telefoonverkopen."
  },
  {
    "slug": "bouwsets-mix",
    "name": "Bouwsets mixpallet",
    "category": "speelgoed",
    "price": 1350.0,
    "msrp": 5200,
    "items": 40,
    "condition": "Nieuw verzegeld",
    "badge": "Nieuw",
    "image": "assets/products/pallet-toys.jpg",
    "short": "Grote bouwdozen, sealed, met setnummers in het manifest.",
    "body": "Hoge herkenning, relatief eenvoudig te listen. Controleer of sets retired zijn; dat staat in de kolom status."
  },
  {
    "slug": "collectible-cards-6",
    "name": "Collectible card case – 6 displays",
    "category": "speelgoed",
    "price": 890.0,
    "msrp": 2400,
    "items": 6,
    "condition": "Nieuw",
    "badge": "Sealed",
    "image": "assets/products/pallet-cards.jpg",
    "short": "Sealed displays voor kaartwinkels en online resellers.",
    "body": "Niet geopend. Foto's van seal en batch waar beschikbaar. Geen pull-garantie."
  },
  {
    "slug": "speelgoed-algemeen-200",
    "name": "Algemeen speelgoed – 200 stuks",
    "category": "speelgoed",
    "price": 760.0,
    "msrp": 3800,
    "items": 200,
    "condition": "Nieuw / overstock",
    "badge": "Beginners",
    "image": "assets/products/pallet-toys.jpg",
    "short": "Toegankelijk instaplot voor nieuwe wederverkopers.",
    "body": "Lage complexiteit, brede doelgroep. Aanbevolen als eerste pallet voordat je naar high-count of salvage gaat."
  },
  {
    "slug": "mystery-electronics",
    "name": "Mystery box elektronica – pallet",
    "category": "mystery-box",
    "price": 640.0,
    "msrp": null,
    "items": null,
    "condition": "As-is",
    "badge": "As-is",
    "image": "assets/products/pallet-mystery.jpg",
    "short": "Gemengde elektronica-retouren zonder volledige SKU-garantie.",
    "body": "Er is een categorieraming, geen artikel-voor-artikel lijst. Koop alleen als je as-is accepteert."
  },
  {
    "slug": "mystery-general",
    "name": "Mystery box algemeen – pallet",
    "category": "mystery-box",
    "price": 520.0,
    "msrp": null,
    "items": null,
    "condition": "As-is",
    "badge": "As-is",
    "image": "assets/products/pallet-mystery.jpg",
    "short": "Huishouden, speelgoed en accessoires in één stapel.",
    "body": "Goedkoop instappen, hoge sorteertijd. Niet hetzelfde als een manifestlot."
  },
  {
    "slug": "airco-retour-40",
    "name": "Airco retouren – 40 stuks (3 pallets)",
    "category": "airco",
    "price": 1203.11,
    "msrp": 12000,
    "items": 40,
    "condition": "Retour",
    "badge": "3 pallets",
    "image": "assets/products/pallet-airco.jpg",
    "short": "Draagbare units uit een retourprogramma. 230V.",
    "body": "Sommige units missen een slang of afstandsbediening. Dat staat per regel. Vracht is hoger door volume; vraag een offerte."
  },
  {
    "slug": "airco-overstock-12",
    "name": "Airco overstock – 12 stuks",
    "category": "airco",
    "price": 1680.0,
    "msrp": 5400,
    "items": 12,
    "condition": "Nieuw",
    "badge": "Nieuw",
    "image": "assets/products/pallet-airco.jpg",
    "short": "Nieuwe draagbare airco's, seizoensclearance.",
    "body": "Schonere lot dan retouren. Beperkt tot de zomerpiek; daarna langzamere exit."
  },
  {
    "slug": "winter-boots-1",
    "name": "Winterlaarzen pallet #1",
    "category": "winterschoenen",
    "price": 900.0,
    "msrp": 4200,
    "items": 72,
    "condition": "Nieuw",
    "badge": "Seizoen",
    "image": "assets/products/pallet-winter.jpg",
    "short": "Gevoerde laarzen, dames en heren, maatoverzicht in Excel.",
    "body": "Seizoensgevoelig. Bestel ruim voor november als je winterpiek wilt meepakken."
  },
  {
    "slug": "winter-boots-2",
    "name": "Winterschoenen pallet #2",
    "category": "winterschoenen",
    "price": 800.0,
    "msrp": 3600,
    "items": 60,
    "condition": "Nieuw / overstock",
    "badge": "Seizoen",
    "image": "assets/products/pallet-sneakers.jpg",
    "short": "Lagere teller, gemengde stijlen.",
    "body": "Bevat enkelhoge en kuit-hoge modellen. Waterdichtheid per model in het manifest."
  },
  {
    "slug": "handtassen-mix",
    "name": "Dameshandtassen mix – 80 stuks",
    "category": "kleding",
    "price": 450.0,
    "msrp": 2400,
    "items": 80,
    "condition": "Nieuw",
    "badge": "Instap",
    "image": "assets/products/pallet-bags.jpg",
    "short": "Toegankelijk lot voor nieuwe modeverkopers.",
    "body": "Geen replica-lederclaims. Materialen staan als PU, textiel of leer volgens het bestand."
  },
  {
    "slug": "tv-salvage-10",
    "name": "TV salvage – 10 stuks",
    "category": "elektronica",
    "price": 740.0,
    "msrp": 5800,
    "items": 10,
    "condition": "Salvage",
    "badge": "Salvage",
    "image": "assets/products/pallet-monitors.jpg",
    "short": "Schermen met schade. Alleen voor technici.",
    "body": "Geen beeldgarantie. Serienummers en inch-maten staan in het manifest."
  },
  {
    "slug": "console-accessoires",
    "name": "Console en accessoires – 35 stuks",
    "category": "elektronica",
    "price": 1560.0,
    "msrp": 6100,
    "items": 35,
    "condition": "Nieuw / retour",
    "badge": "Manifest",
    "image": "assets/products/pallet-electronics.jpg",
    "short": "Controllers, headsets en gesealde accessoires.",
    "body": "Geen garantie dat consoles zelf in het lot zitten. Lees de SKU-lijst voordat je uitgaat van hardware."
  }
];
